package info.phosco.forms.translate.element.datablock;

import info.phosco.forms.translate.element.FormProperties;

public enum DataBlockAttributes implements FormProperties {

	NAME,
	OFFSET,
	QUERY_ARRAY_SIZE,
	NUMBER_RECORDS_DISPLAYED,
	NUMBER_RECORDS_BUFFERED,
	QUERY_ALL_RECORDS,
	RECORD_ORIENTATION,
	SINGLE_RECORD,
	NAVIGATION_STYLE,
	PREV_NAV_DATA_BLOCK,
	NEXT_NAV_DATA_BLOCK,
	WHERE_CLAUSE,
	ORDER_CLAUSE,
	ALIAS,
	INSERT_ALLOWED,
	UPDATE_ALLOWED,
	LOCKING_MODE,
	DELETE_ALLOWED,
	KEY_MODE,
	MAX_QUERY_TIME,
	MAX_RECORDS_FETCHED,
	QUERY_ALLOWED,
	DATABASE_DATA_BLOCK,
	DATA_BLOCK_DESCR,
	LIST_IN_DATA_BLOCK_MENU,
	DIRECTION;
}
